TOPICS = [
    ("Biryani", "印度香饭"),
    ("Borscht", "罗宋汤"),
    ("Buddha Jumps Over the Wall", "佛跳墙"),
    ("Bun cha", "烤肉米粉"),
    ("Century egg", "皮蛋"),
    ("Char siu", "叉燒"),
    ("Dandan noodles", "担担面"),
    ("Dolma", "朵爾瑪"),
    ("Dosa (food)", "多薩"),
    ("Douhua", "豆花"),
    ("Fufu", "富富"),
    ("Goulash", "匈牙利湯"),
    ("Injera", "英杰拉"),
    ("Jianbing", "煎饼"),
    ("Jollof rice", "加羅夫飯"),
    ("Khachapuri", "卡查普里"),
    ("Kimchi", "韓式泡菜"),
    ("Laksa", "叻沙"),
    ("Mapo tofu", "麻婆豆腐"),
    ("Mooncake", "月饼"),
    ("Moussaka", "木莎卡"),
    ("Paella", "西班牙鐵鍋飯"),
    ("Peking duck", "北京烤鸭"),
    ("Pho", "越南粉"),
    ("Pierogi", "波蘭餃子"),
    ("Poutine", "盖浇薯条"),
    ("Rendang", "仁当"),
    ("Satay", "沙嗲"),
    ("Shawarma", "沙威玛"),
    ("Stinky tofu", "臭豆腐"),
    ("Surströmming", "瑞典鹽醃鯡魚"),
    ("Tagine", "塔吉鍋"),
    ("Tom yum", "冬蔭"),
    ("Wiener schnitzel", "维也纳炸牛排"),
    ("Wonton", "馄饨"),
    ("Xiaolongbao", "小籠包"),
    ("Onigiri", "御握"),
    ("Yakisoba", "日式炒麵"),
    ("Yakitori", "日式烤雞串"),
    ("Zonzi", "粽"),
    ("Kaiserschmarrn","皇帝煎餅"),
    ("Baklava", "巴克拉瓦"),
    ("Frybread","炸面包 (美洲)"),
    ("Nattō","納豆"),
    ("Sauerbraten","酸味燉牛肉"),
    ("Dobos torte","多層蛋糕"),
    ("Churro","西班牙油條"),
    ("Tiramisu","提拉米蘇"),
    ("Earl Grey tea","格雷伯爵茶"),
    ("Kulfi","库尔菲"),
    ("Halo-halo","哈囉哈囉"),
    ("Oolong","乌龙茶")

]